name:                homework02
version:             0.1.0.0

ghc-options:
- -Wall
- -Werror
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  homework02-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - homework02
    - hspec
    - QuickCheck
    - generic-random
    - containers
    - process
    - extra
    - bytestring
